/*

Campus Device Loan System

Cloud Native DevOps (CIS3039-N)

Author: Arshad Aslam

Student ID: K0352250

Teesside University

Worker Service

Processes reservation and device return events generated by the API service.

*/

const fs = require("fs")

const path = require("path")

console.log("Worker service started")

const eventFile = path.join(__dirname, "reservation-event.json")

function processEvent() {

    if (!fs.existsSync(eventFile)) {

        console.log("No reservation event found")

        console.log("Worker service completed event cycle")

        return

    }

    try {

        const eventData = JSON.parse(fs.readFileSync(eventFile, "utf8"))

        console.log("Event detected by worker")

        console.log("Event type:", eventData.type)

        if (eventData.type === "reservation_created") {

            console.log("Processing reservation event")

            console.log(`Device reserved: ${eventData.deviceName}`)

            console.log(`Remaining availability: ${eventData.available}`)

            console.log(`Expected return date: ${eventData.returnDate}`)

        }

        if (eventData.type === "device_returned") {

            console.log("Processing device return event")

            console.log(`Device returned: ${eventData.deviceName}`)

            console.log(`Available units now: ${eventData.available}`)

        }

        console.log("Worker processing complete")

        fs.unlinkSync(eventFile)

        console.log("Event file removed after processing")

        console.log("Worker service completed event cycle")

    } catch (error) {

        console.error("Worker failed to process event:", error.message)

    }

}

processEvent()
 