/*
Campus Device Loan System
Cloud Native DevOps (CIS3039-N)
Author: Arshad Aslam
Student ID: K0352250
Teesside University
Worker Service
Processes reservation events generated by the API service.
*/
const fs = require("fs")
console.log("Worker service started")
const eventFile = "reservation-event.json"
if (fs.existsSync(eventFile)) {
 const eventData = JSON.parse(fs.readFileSync(eventFile, "utf8"))
 console.log("Worker processed reservation event:", eventData)
} else {
 console.log("No reservation event found")
}